-- CreateTable
CREATE TABLE "about_page_content" (
    "id" TEXT NOT NULL,
    "heroEyebrow" TEXT NOT NULL,
    "heroTitle" TEXT NOT NULL,
    "heroDescription" TEXT NOT NULL,
    "heroButtonLabel" TEXT NOT NULL,
    "heroImageUrl" TEXT,
    "heroImageFileKey" TEXT,
    "spiritEyebrow" TEXT NOT NULL,
    "spiritTitle" TEXT NOT NULL,
    "spiritFirstParagraph" TEXT NOT NULL,
    "spiritSecondParagraph" TEXT NOT NULL,
    "spiritHandwritten" TEXT NOT NULL,
    "spiritImageUrl" TEXT,
    "spiritImageFileKey" TEXT,
    "philosophyEyebrow" TEXT NOT NULL,
    "philosophyTitle" TEXT NOT NULL,
    "philosophyDescription" TEXT NOT NULL,
    "philosophyFirstTitle" TEXT NOT NULL,
    "philosophyFirstDescription" TEXT NOT NULL,
    "philosophySecondTitle" TEXT NOT NULL,
    "philosophySecondDescription" TEXT NOT NULL,
    "philosophyThirdTitle" TEXT NOT NULL,
    "philosophyThirdDescription" TEXT NOT NULL,
    "philosophyFourthTitle" TEXT NOT NULL,
    "philosophyFourthDescription" TEXT NOT NULL,
    "statsEyebrow" TEXT NOT NULL,
    "statsTitle" TEXT NOT NULL,
    "ctaEyebrow" TEXT NOT NULL,
    "ctaTitle" TEXT NOT NULL,
    "ctaDescription" TEXT NOT NULL,
    "ctaButtonLabel" TEXT NOT NULL,
    "ctaImageUrl" TEXT,
    "ctaImageFileKey" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "about_page_content_pkey" PRIMARY KEY ("id")
);
